feat: add lyra testing
Signed-off-by: Raif Coonjah <raifcoonjah@proton.me>

diff --git a/.github/workflows/test-lyra.yml b/.github/workflows/test-lyra.yml
--- a/.github/workflows/test-lyra.yml
+++ b/.github/workflows/test-lyra.yml
@@ -6,9 +6,9 @@ name: simple-lyra-test
 on:
   # Triggers the workflow on push or pull request events but only for the "master" branch
   push:
-    branches: [ "master" ]
+    branches: ["master"]
   pull_request:
-    branches: [ "master" ]
+    branches: ["master"]
 
   # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
@@ -32,5 +32,9 @@ jobs:
       # Runs a set of commands using the runners shell
       - name: Run a multi-line script
         run: |
-          echo Add other actions to build,
-          echo test, and deploy your project.
+          if ./lyra; then
+              echo "Test success, Lyra executed with success."
+          else 
+              echo "Error: Lyra did not execute properly."
+              exit 1
+          fi
